In [1]:
import sys
print(sys.executable)

/home/kmann/DH_project_webpage_pub/venv/bin/python

In [2]:
%pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

# import dataset
df = pd.read_csv('/home/kmann/DH_project_webpage_pub/historical-popculture-artifacts-american-history - Sheet1.csv')
print("all rows:")
df

all rows:

,product_name,manufacturer,product_type,first_year_sold,historical_type,type_name,packaging_text,package_description
0,tactics,theavalongamecompany,boardgame,1954,event,wwii,"Tactics The new, realistic land army war game!...",rectangular cardboard box with black backgroun...
1,gettysburg,theavalongamecompany,boardgame,1958,event,gettysburg,gettysburg now you fight the civil war battle ...,rectangular cardboard box with white and blue ...
2,stalingrad,theavalongamecompany,boardgame,1963,event,stalingrad,stalingrad campaign in russia 1941-45,rectangular cardboard box with black and white...
3,annieoakleygame,miltonbradley,boardgame,1955,figure,annieoakley,another mb milton bradley key to fun and learn...,rectangular cardboard box with clay path large...

In [5]:
# Clean the dataset by making all values packaging_text to lowercase
df['packaging_text'] = df['packaging_text'].str.lower()
print("cleaned dataset:")
df

cleaned dataset:

,product_name,manufacturer,product_type,first_year_sold,historical_type,type_name,packaging_text,package_description
0,tactics,theavalongamecompany,boardgame,1954,event,wwii,"tactics the new, realistic land army war game!...",rectangular cardboard box with black backgroun...
1,gettysburg,theavalongamecompany,boardgame,1958,event,gettysburg,gettysburg now you fight the civil war battle ...,rectangular cardboard box with white and blue ...
2,stalingrad,theavalongamecompany,boardgame,1963,event,stalingrad,stalingrad campaign in russia 1941-45,rectangular cardboard box with black and white...
3,annieoakleygame,miltonbradley,boardgame,1955,figure,annieoakley,another mb milton bradley key to fun and learn...,rectangular cardboard box with clay path large...

In [6]:
# Make values in first_year_sold integers
df['first_year_sold'] = df['first_year_sold'].astype(int)
print("dataset with first_year_sold as integers:")
df

dataset with first_year_sold as integers:

,product_name,manufacturer,product_type,first_year_sold,historical_type,type_name,packaging_text,package_description
0,tactics,theavalongamecompany,boardgame,1954,event,wwii,"tactics the new, realistic land army war game!...",rectangular cardboard box with black backgroun...
1,gettysburg,theavalongamecompany,boardgame,1958,event,gettysburg,gettysburg now you fight the civil war battle ...,rectangular cardboard box with white and blue ...
2,stalingrad,theavalongamecompany,boardgame,1963,event,stalingrad,stalingrad campaign in russia 1941-45,rectangular cardboard box with black and white...
3,annieoakleygame,miltonbradley,boardgame,1955,figure,annieoakley,another mb milton bradley key to fun and learn...,rectangular cardboard box with clay path large...

In [7]:
# Change column name from 'first_year_sold' to 'year'
df.rename(columns={'first_year_sold': 'year'}, inplace=True)
print("dataset with column name changed to 'year':")
df

dataset with column name changed to 'year':

,product_name,manufacturer,product_type,year,historical_type,type_name,packaging_text,package_description
0,tactics,theavalongamecompany,boardgame,1954,event,wwii,"tactics the new, realistic land army war game!...",rectangular cardboard box with black backgroun...
1,gettysburg,theavalongamecompany,boardgame,1958,event,gettysburg,gettysburg now you fight the civil war battle ...,rectangular cardboard box with white and blue ...
2,stalingrad,theavalongamecompany,boardgame,1963,event,stalingrad,stalingrad campaign in russia 1941-45,rectangular cardboard box with black and white...
3,annieoakleygame,miltonbradley,boardgame,1955,figure,annieoakley,another mb milton bradley key to fun and learn...,rectangular cardboard box with clay path large...

In [8]:
# Remove puncuation from values in packaging_text
df['packaging_text'] = df['packaging_text'].str.replace('[^\w\s]', '', regex=True)
print("dataset with punctuation removed from packaging_text:")
df

dataset with punctuation removed from packaging_text:

,product_name,manufacturer,product_type,year,historical_type,type_name,packaging_text,package_description
0,tactics,theavalongamecompany,boardgame,1954,event,wwii,tactics the new realistic land army war game d...,rectangular cardboard box with black backgroun...
1,gettysburg,theavalongamecompany,boardgame,1958,event,gettysburg,gettysburg now you fight the civil war battle ...,rectangular cardboard box with white and blue ...
2,stalingrad,theavalongamecompany,boardgame,1963,event,stalingrad,stalingrad campaign in russia 194145,rectangular cardboard box with black and white...
3,annieoakleygame,miltonbradley,boardgame,1955,figure,annieoakley,another mb milton bradley key to fun and learn...,rectangular cardboard box with clay path large...

In [9]:
# Save dataset to new csv file
df.to_csv('/home/kmann/DH_project_webpage_pub/cleaned_historical_popculture_artifacts.csv', index=False)
print("Dataset saved to cleaned_historical_popculture_artifacts.csv")

Dataset saved to cleaned_historical_popculture_artifacts.csv